# Site settings
title: "Oscar Marin Personal Website"
description: "Welcome to my personal website where I share insights, projects, and more."
author:
  name: "Marin"
  email: "mysite@marin.cr"

# URL settings
url: "https://marin.cr"
baseurl: "" # Leave this empty since you're using a custom domain

# Theme settings
theme: jekyll-theme-minimal

# Social media links (optional)
social_links:
  github:  marinoscar
  linkedin: marinoscar
  twitter: marin_cr

# Google Analytics (optional)
google_analytics: UA-XXXXXXXXX-X

# Build settings
markdown: kramdown
