# Site settings
title: "Oscar Marin Personal Website"
description: "Welcome to my personal website where I share insights, projects, and more."
author:
  name: "Oscar Marin"
  email: "mysite@marin.cr"

# URL settings
url: "https://marin.cr"
baseurl: "" # Leave this empty since you're using a custom domain

# Theme settings
theme: jekyll-theme-minimal

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
    

# Social media links (optional)
social_links:
  github:  marinoscar
  linkedin: marinoscar
  twitter: marin_cr

# Google Analytics (optional)
google_analytics: UA-XXXXXXXXX-X

# Build settings
# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  
# How to display the link to your website in the footer
url-pretty: "marin.cr"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false
